use_default_settings: true

general:
  instance_name: "Hermes Search"

search:
  safe_search: 0
  autocomplete: "google"
  default_lang: "zh-CN"

server:
  secret_key: "CHANGE_ME_$(openssl rand -hex 32)"
  bind_address: "0.0.0.0"
  port: 8080

ui:
  static_use_hash: true

redis:
  url: "redis://redis:6379/0"
